### ISSUE TITLE
finish pathtracer tutorial plz

### ISSUE THREAD

**Issue by collerblade2** [LWJGL/lwjgl3-wiki#4]
hello,
im intersted in the path tracer demo you have started. Is there any chance to contiune that tutorial?
Is there any unpublished code? you have shown a final image, but no code to generate it.
Thanks:
collerblade

**Comment by httpdigest** [comment]
It's unlikely that the tutorial will be continued. It's a mystery to me today how I was able to find that kind of motivation to pull off something like this in the first place. I've since tried to get that back. :)
You can have a look at the [lwjgl3-demos](https://github.com/LWJGL/lwjgl3-demos/tree/master/src/org/lwjgl/demo/opengl/raytracing) repository. It contains some demos extending far beyond what was explained in the written tutorial, such as [an implementation](https://github.com/LWJGL/lwjgl3-demos/blob/master/src/org/lwjgl/demo/opengl/raytracing/DemoSsboTrianglesStacklessKdTree.java) of the algorithm described in the "Stackless KD-Tree Traversal for High Performance GPU Ray Tracing" paper to accelerate tracing triangle meshes, as well as hybrid rasterization and path tracing to further accelerate things.
Thanks for you interest in the article, though!

**Comment by collerblade2** [comment]
Ok, i understand. Ty for your time.

**Comment by httpdigest** [comment]
If you are interested in the topic in general and want to keep learning more in-depth, then I highly recommend the two books mentioned at the end of the first article.

**Comment by httpdigest** [comment]
One more thing: There is the Scratchapixel site and its authors do an outstanding job of explaining computer graphics including the foundations of ray tracing. They've done a much better job than I would've done, had I continued with the LWJGL tutorial since the following would have had to come next: https://www.scratchapixel.com/lessons/mathematics-physics-for-computer-graphics/monte-carlo-methods-mathematical-foundations
Please browse around that site as well. It contains very well written articles.
