### ISSUE TITLE
glGenBuffers(int, IntBuffer) no longer exists

### ISSUE THREAD

**Issue by nanodeath** [LWJGL/lwjgl3-wiki#6]
I'm trying to follow along in the [1.3 Memory FAQ](https://github.com/LWJGL/lwjgl3-wiki/wiki/1.3.-Memory-FAQ) tutorial, and near the middle there's a line of code `glGenBuffers(1, ip);`, but as far as I can tell, that method no longer exists (3.1.6). It's hard to tell exactly where I should be looking, because none of the examples have imports, but I was expecting to find it around [here](https://javadoc.lwjgl.org/org/lwjgl/opengl/GL15.html#glGenBuffers-java.nio.IntBuffer-). If I just drop the int parameter, I get a JVM crash. Suggestions?

Thanks!

**Comment by Spasi** [comment]
Thanks, fixed with [5049efa](https://github.com/LWJGL/lwjgl3-wiki/wiki/1.3.-Memory-FAQ/5049efae7fa913a1c5bcfc4265c11a8a3a297ac7).

LWJGL methods that accept buffers are usually _auto-sized_. This means that when there's another parameter that defines how big a buffer parameter is, LWJGL automatically passes the correct value there, properly derived from the buffer's number of `.remaining()` elements.

Dropping the int parameter should not cause a crash. In order to identify the issue, try:

- Enabling LWJGL's debug mode with `-Dorg.lwjgl.util.Debug=true`.
- Using a debug OpenGL context and registering a debug callback (see [GLUtil.setupDebugMessageCallback](https://github.com/LWJGL/lwjgl3/blob/master/modules/lwjgl/opengl/src/main/java/org/lwjgl/opengl/GLUtil.java#L31)).
- Running your app with the [LWJGLX/debug](https://github.com/LWJGLX/debug) agent.

**Comment by nanodeath** [comment]
Turned out to be user error, of course -- if you try to run examples from that particular page, without doing all the setup mentioned on the [OpenGL](https://github.com/LWJGL/lwjgl3-wiki/wiki/2.2.-OpenGL) page, well...turns out some of that initialization logic is kinda important!

Thanks for updating the docs.
